{
 "title": "Main dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "server", "query": "artillery-api" },
   {
    "name": "container",
    "query": "tp1-arqui-software_node_1, tp1-arqui-software_node_2, tp1-arqui-software_node_3, tp1-arqui-software_cadvisor_1, tp1-arqui-software_grafana_1, tp1-arqui-software_graphite_1,  tp1-arqui-software_nginx_1, tp1-arqui-software_bbox_1"
   }
  ]
 },
 "panels": [
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Endpoint throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "target": "alias(stats_counts.api_metrics.request.received.increment.dictionary, 'dictionary troughput')"
    },
    {
     "target": "alias(stats_counts.api_metrics.request.received.increment.quote, 'quotes troughput')"
    },
    {
     "target": "alias(stats_counts.api_metrics.request.received.increment.spaceflight_news, 'spaceflights troughput')"
    }
   ]
  },
  { "title": "Custom metrics - Total time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Dictionary - Total response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "target": "alias(stats.gauges.api_metrics.dictionary.total.time, 'Response time (ms)')"
    }
   ]
  },
  {
   "title": "Dictionary - Total response time (timing)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "target": "alias(stats.timers.api_metrics.dictionary.total.time.median, 'median (ms)')"
    },
    {
     "target": "alias(stats.timers.api_metrics.dictionary.total.time.upper_90, 'p90 (ms)')"
    },
    {
     "target": "alias(stats.timers.api_metrics.dictionary.total.time.mean, 'avg (ms)')"
    }
   ]
  },
  {
   "title": "Spaceflight news - Total response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "target": "alias(stats.gauges.api_metrics.spaceflight_news.total.time, 'Response time (ms)')"
    }
   ]
  },
  {
   "title": "Spaceflight news - Total response time (timing)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "target": "alias(stats.timers.api_metrics.spaceflight_news.total.time.median, 'median (ms)')"
    },
    {
     "target": "alias(stats.timers.api_metrics.spaceflight_news.total.time.upper_90, 'p90 (ms)')"
    },
    {
     "target": "alias(stats.timers.api_metrics.spaceflight_news.total.time.mean, 'avg (ms)')"
    }
   ]
  },
  {
   "title": "Quotes - Total response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "target": "alias(stats.gauges.api_metrics.quote.total.time, 'Response time (ms)')"
    }
   ]
  },
  {
   "title": "Quotes - Total response time (timing)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "target": "alias(stats.timers.api_metrics.quote.total.time.median, 'median (ms)')"
    },
    {
     "target": "alias(stats.timers.api_metrics.quote.total.time.upper_90, 'p90 (ms)')"
    },
    {
     "target": "alias(stats.timers.api_metrics.quote.total.time.mean, 'avg (ms)')"
    }
   ]
  },
  {
   "title": "Custom metrics - Depenencies time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 }
  },
  {
   "title": "Dictionary - Dependency response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "target": "alias(stats.gauges.api_metrics.dictionary.dependency.time, 'Dependency response time (ms)')"
    }
   ]
  },
  {
   "title": "Dictionary - Dependency response time (timing)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "target": "alias(stats.timers.api_metrics.dictionary.dependency.time.median, 'median (ms)')"
    },
    {
     "target": "alias(stats.timers.api_metrics.dictionary.dependency.time.upper_90, 'p90 (ms)')"
    },
    {
     "target": "alias(stats.timers.api_metrics.dictionary.dependency.time.mean, 'avg (ms)')"
    }
   ]
  },
  {
   "title": "Space flight news - Dependency response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "target": "alias(stats.gauges.api_metrics.spaceflight_news.dependency.time, 'Dependency response time (ms)')"
    }
   ]
  },
  {
   "title": "Spaceflight news - Dependency response time (timing)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "target": "alias(stats.timers.api_metrics.spaceflight_news.dependency.time.median, 'median (ms)')"
    },
    {
     "target": "alias(stats.timers.api_metrics.spaceflight_news.dependency.time.upper_90, 'p90 (ms)')"
    },
    {
     "target": "alias(stats.timers.api_metrics.spaceflight_news.dependency.time.mean, 'avg (ms)')"
    }
   ]
  },
  {
   "title": "Quotes - Dependency response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "target": "alias(stats.gauges.api_metrics.quote.dependency.time, 'Dependency response time (ms)')"
    }
   ]
  },
  {
   "title": "Quotes - Dependency response time (timing)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "target": "alias(stats.timers.api_metrics.quote.dependency.time.median, 'median (ms)')"
    },
    {
     "target": "alias(stats.timers.api_metrics.quote.dependency.time.upper_90, 'p90 (ms)')"
    },
    {
     "target": "alias(stats.timers.api_metrics.quote.dependency.time.mean, 'avg (ms)')"
    }
   ]
  },
  {
   "title": "Cache metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dictionary Cache hits over time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "target": "alias(stats_counts.api_metrics.cache.hit.increment, 'cache_hit')"
      }
     ]
    },
    {
     "title": "Dictionary Cache hits over time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "target": "aliasByMetric(stats.gauges.api_metrics.cache.hit)"
      }
     ]
    }
   ]
  },
  {
   "title": "Status codes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "collapsed": true,
   "panels": [
    {
     "title": "Artillery - All status codes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "target": "aliasByMetric(stats.gauges.artillery-api.codes.*)"
      }
     ]
    },
    {
     "title": "Artillery - Rate limit error ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "target": "alias(stats.gauges.artillery-api.codes.503, 'Rate limit errors (503)')"
      }
     ]
    },
    {
     "title": "Artillery - 2xx Status codes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "target": "aliasByMetric(stats.gauges.artillery-api.codes.200)"
      }
     ]
    },
    {
     "title": "Artillery - Time outs received - Gauge",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "target": "aliasByMetric(stats.gauges.artillery-api.errors.ETIMEDOUT)"
      }
     ]
    },
    {
     "title": "Artillery - All status codes - Max value Gauge",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "target": "aliasByMetric(stats.gauges.artillery-api.codes.*)"
      }
     ]
    },
    {
     "title": "Artillery - All status codes - Sum Bar Gauge",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "target": "aliasByMetric(stats.gauges.artillery-api.codes.*)"
      }
     ]
    },
    {
     "title": "Artillery - Time outs received -Sum Gauge",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "target": "aliasByMetric(stats.gauges.artillery-api.errors.ETIMEDOUT)"
      }
     ]
    },
    {
     "title": "Artillery - All status codes - Count Bar Gauge",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "count" ] } },
     "targets": [
      {
       "target": "aliasByMetric(stats.gauges.artillery-api.codes.*)"
      }
     ]
    }
   ]
  },
  {
   "title": "Artillery metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scenarios launched (stacked)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "target": "aliasByMetric(stats.gauges.$server.scenarioCounts.*)"
      }
     ]
    },
    {
     "title": "Requests state (stacked)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "alias(sumSeries(stats.gauges.$server.errors.*), 'Errored')"
      },
      {
       "target": "alias(stats.gauges.$server.codes.200, 'Completed')"
      },
      {
       "target": "alias(stats.gauges.$server.pendingRequests, 'Pending')"
      },
      {
       "target": "alias(stats.gauges.$server.codes.429, 'Limited')"
      }
     ]
    },
    {
     "title": "Response time (client-side)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "target": "alias(stats.gauges.$server.scenarioDuration.max, 'Upper')"
      },
      {
       "target": "alias(stats.gauges.$server.scenarioDuration.median, 'Median')"
      },
      {
       "target": "alias(stats.gauges.$server.scenarioDuration.mean, 'avg')"
      }
     ]
    }
   ]
  },
  {
   "title": "Resources metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true,
   "panels": [
    {
     "title": "Resources",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "target": "alias(removeBelowValue(asPercent(derivative(keepLastValue(stats.gauges.cadvisor.$container.cpu_cumulative_usage, 100)), 10000000000), 0.0001), 'CPU')"
      },
      {
       "target": "alias(asPercent(stats.gauges.cadvisor.$container.memory_working_set, 34359738368), 'Memory')"
      }
     ]
    },
    {
     "title": "CPU by instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "target": "alias(removeBelowValue(asPercent(derivative(keepLastValue(stats.gauges.cadvisor.tp1-arqui-software_node*.cpu_cumulative_usage, 100)), 10000000000), 0.0001), 'CPU')"
      }
     ]
    },
    {
     "title": "Memory max usage by instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "target": "alias(asPercent(stats.gauges.cadvisor.tp1-arqui-software_node*.memory_max_usage, 34359738368), 'memory_max_usage')"
      }
     ]
    },
    {
     "title": "Memory working set by instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "target": "alias(asPercent(stats.gauges.cadvisor.tp1-arqui-software_node*.memory_working_set, 34359738368), 'memory_working_set')"
      }
     ]
    }
   ]
  }
 ]
}